# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BookStore_Gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
import sys
BookStore = sqlite3.connect('BookStore.db')
cursbs = BookStore.cursor()


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(484, 379)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.BookTitle = QtWidgets.QLabel(Form)
        self.BookTitle.setObjectName("BookTitle")
        self.verticalLayout.addWidget(self.BookTitle)
        self.Title = QtWidgets.QLineEdit(Form)
        self.Title.setFrame(True)
        self.Title.setObjectName("Title")
        self.verticalLayout.addWidget(self.Title)
        self.PriceB = QtWidgets.QPushButton(Form)
        self.PriceB.setObjectName("PriceB")
        self.PriceB.clicked.connect(self.get_price)
        self.verticalLayout.addWidget(self.PriceB)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.price = QtWidgets.QLabel(Form)
        self.price.setObjectName("price:")
        self.horizontalLayout.addWidget(self.price)
        self.Display_price = QtWidgets.QLineEdit(Form)
        self.Display_price.setEnabled(False)
        self.Display_price.setFrame(False)
        self.Display_price.setObjectName("Display_price")
        self.horizontalLayout.addWidget(self.Display_price)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.Quantity = QtWidgets.QLabel(Form)
        self.Quantity.setObjectName("Quantity")
        self.verticalLayout.addWidget(self.Quantity)
        self.Qty = QtWidgets.QLineEdit(Form)
        self.Qty.setInputMask("")
        self.Qty.setProperty("Integer", 0)
        self.Qty.setObjectName("Qty")
        self.Qty.setValidator(QtGui.QIntValidator())
        self.verticalLayout.addWidget(self.Qty)
        self.TotalB = QtWidgets.QPushButton(Form)
        self.TotalB.setObjectName("TotalB")
        self.TotalB.clicked.connect(self.get_total)
        self.verticalLayout.addWidget(self.TotalB)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.total = QtWidgets.QLabel(Form)
        self.total.setObjectName("total")
        self.horizontalLayout_2.addWidget(self.total)
        self.Display_Total = QtWidgets.QLineEdit(Form)
        self.Display_Total.setEnabled(False)
        self.Display_Total.setFrame(False)
        self.Display_Total.setObjectName("Display_Total")
        self.horizontalLayout_2.addWidget(self.Display_Total)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "BookStore"))
        self.BookTitle.setText(_translate("Form", "Book Title"))
        self.PriceB.setText(_translate("Form", "Find Price"))
        self.price.setText(_translate("Form", "Price :"))
        self.Quantity.setText(_translate("Form", "Quantity"))
        self.TotalB.setText(_translate("Form", "Find Total"))
        self.total.setText(_translate("Form", "Total :"))

        
    def get_price(self):
        txt = self.Title.text()
        try:
            
            cursbs.execute("SELECT Price FROM Books WHERE Title = '"+txt+"';")
            rcd = cursbs.fetchone()
            print("Rs.: %d"%(rcd))
            self.Display_price.setText("Rs. %d"%(rcd))
        except:
            self.Display_price.setText("Book Not Found!")

    def get_total(self):
        txt = self.Title.text()
        t = int(self.Qty.text())
        cursbs.execute("SELECT Price FROM Books WHERE Title = '"+txt+"';")
        rcd = list(cursbs.fetchone())
        a = rcd[0]
        tot = t * a
        print("Rs.: %d"%(tot))
        self.Display_Total.setText("Rs. %d"%(tot))

        

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
